name: Falster
favicon: null
layout_spectrum: 0.648981026140973
typography_spectrum: 0.6856191400438547
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.2942829290404916
  lightness: 0.5879958970472217
  saturation: 0.280383720761165
  rhythmicContrast: 0.5522435712628067
purpose: []
