name: Falster
favicon: null
layout_spectrum: 1
typography_spectrum: 0.49844
title: Falster
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#64adf1'
    - '#1e2b11'
    - '#f4f3f1'
    - '#a9a041'
    - '#82775b'
  brandStrength: 0.2942829290404916
  lightness: 0.5879958970472217
  saturation: 0.280383720761165
  rhythmicContrast: 0.5
purpose: []
